name: My Workflow

# Erweiterte Berechtigungen für den Workflow
permissions:
  contents: write
  actions: read
  checks: write

on:
  push:
    branches:
    - '*'
    - '!status'

jobs:
  update-points-bar:
    uses: markpatterson27/points-bar/.github/workflows/reusable-workflow.yml@main
    permissions:
      contents: write
    with:
      points: '10/20'
      path: 'icons/points-bar.svg'  # Angepasst für deinen README-Link
      type: 'bar'
      bar-color: '#4c1'
      bar-background: '#555'
      font-color: '#aaa'
      label: 'Points'
      width: '100'
      reverse: false
      branch: status
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
