name: My Workflow

# Erweiterte Berechtigungen für den Workflow
permissions:
  contents: write
  actions: read
  checks: write

on:
  push:
    branches:
    - '*'
    - '!status'

jobs:
  # Job zum Löschen der alten Datei vor dem Update
  cleanup-old-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: status  # Checkout des status branch
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Delete old points bar if exists
        run: |
          if [ -f "icons/points-bar.svg" ]; then
            rm icons/points-bar.svg
            echo "Old points bar deleted"
          else
            echo "No old points bar found"
          fi
      
      - name: Commit deletion
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Clean up old points bar" || echo "Nothing to commit"
          git push origin status

  update-points-bar:
    needs: cleanup-old-badge  # Wartet auf cleanup
    uses: markpatterson27/points-bar/.github/workflows/reusable-workflow.yml@main
    permissions:
      contents: write
    with:
      points: '20/24'
      path: 'icons/points-bar.svg'  # Angepasst für deinen README-Link
      type: 'bar'
      bar-color: '#4c1'
      bar-background: '#555'
      font-color: '#aaa'
      label: 'Points'
      width: '100'
      reverse: false
      branch: status
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
