name: Generate Points Bar

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Points Bar in README
        uses: markpatterson27/points-bar@v1
        with:
          autograding-json: .github/classroom/autograding.json
          token: ${{ secrets.GITHUB_TOKEN }}
